export type Lang = "pt" | "en";

export const copy = {
  pt: {
    nav: {
      work: "TRABALHOS",
      profile: "PERFIL",
      systems: "SISTEMAS",
      aurhea: "AURHEA",
      contact: "CONTATO",
      menu: "MENU",
      close: "FECHAR",
      openMenu: "Abrir menu de navegação",
      closeMenu: "Fechar menu de navegação",
      skip: "Ir para o conteúdo",
      langLabel: "Alternar idioma para inglês",
    },
    hero: {
      tag: "AR / 2026",
      place: "CAXIAS DO SUL · BRASIL",
      status: "ABERTO A OPORTUNIDADES",
      disciplines: ["SOFTWARE", "SYSTEMS", "AUTOMATION", "OPERATIONS"],
      headline: "Desenvolvo produtos digitais",
      headlineAccent: "para operações do mundo real.",
      portraitAlt: "Retrato de Antony Rodrigues",
      ctaWork: "TRABALHOS SELECIONADOS",
      ctaContact: "INICIAR UM PROJETO",
      explore: "EXPLORAR",
    },
    marquee: [
      "SOFTWARE",
      "SYSTEMS",
      "AUTOMATION",
      "OPERATIONS",
      "PRODUCT",
      "FULL STACK",
      "AURHEA",
    ],
    manifesto: {
      label: "02 / MANIFESTO",
      line1: "SOFTWARE NÃO É",
      line2: "O PONTO DE PARTIDA.",
      accent: "A operação é.",
      quote:
        "Eu não comecei no software. Comecei onde o software precisa funcionar.",
    },
    proof: {
      label: "03 / CREDIBILIDADE",
      title: "O QUE SUSTENTA O TRABALHO",
      items: [
        {
          k: "AURHEA",
          v: "Founder & Developer",
          d: "Empresa de tecnologia própria, fundada em março de 2026.",
        },
        {
          k: "OPERAÇÕES",
          v: "Logística · Indústria",
          d: "Anos dentro de processos reais antes de escrever software para eles.",
        },
        {
          k: "PRODUÇÃO",
          v: "Projetos em uso real",
          d: "Sites, sistemas e plataformas entregues e rodando para clientes.",
        },
        {
          k: "FORMAÇÃO",
          v: "Engenharia de Software — FSG",
          d: "Graduação iniciada em 2025. Base técnica em logística pelo SENAI.",
        },
      ],
    },
    systems: {
      label: "04 / SISTEMAS SELECIONADOS",
      title: "COMO CONSTRUO SISTEMAS",
      intro:
        "Arquitetura pensada a partir do processo, não da tecnologia. Abaixo, o desenho conceitual do principal case técnico.",
      caseTitle: "PORCO MORTO",
      caseSub: "RESTAURANT OPERATIONS SYSTEM",
      flow: [
        "STOREFRONT",
        "ENVIO DO PEDIDO",
        "BACKEND AUTORITATIVO",
        "POSTGRESQL",
        "REALTIME",
        "ADMIN",
        "FINANCEIRO / IMPRESSÃO / OPERAÇÃO",
      ],
      pillars: [
        { t: "BACKEND AUTORITATIVO", d: "Regras de negócio validadas no servidor, nunca no cliente." },
        { t: "DADOS E ACESSO", d: "PostgreSQL com políticas de acesso por linha e autenticação." },
        { t: "REALTIME", d: "Pedidos e status propagados para a operação em tempo real." },
        { t: "CONFIABILIDADE", d: "Idempotência de pedidos, rate limiting e validação de entrada." },
      ],
    },
    work: {
      label: "05 / TRABALHOS SELECIONADOS",
      title: "PROJETOS",
      intro: "Produto, design e desenvolvimento independentes — 2026.",
      view: "VER PROJETO",
      soon: "PREVIEW PRIVADO",
      noLink: "Case interno · sem URL pública",
    },
    timeline: {
      label: "06 / TRAJETÓRIA",
      title: "DE OPERAÇÕES PARA SOFTWARE.",
      steps: [
        { k: "LOGÍSTICA", v: "SENAI — formação técnica" },
        { k: "OPERAÇÕES DE CAMPO", v: "Expresso São Miguel" },
        { k: "OPERAÇÕES INDUSTRIAIS", v: "SV Engenharia e Serviços — atual" },
        { k: "SOFTWARE", v: "Engenharia de Software — FSG, desde 2025" },
        { k: "AURHEA", v: "Founder & Developer — mar/2026" },
      ],
    },
    story: {
      label: "07 / HISTÓRIA",
      title: "O PROBLEMA VEM ANTES DA TECNOLOGIA.",
      paragraphs: [
        "Minha trajetória não começou no software. Começou em operações reais — logística, movimentação de materiais, estoque e ambiente industrial.",
        "Foi entendendo como processos funcionam na prática que comecei a enxergar a tecnologia de outra forma: não como fim, mas como ferramenta para organizar, automatizar e construir negócios melhores.",
        "Hoje conecto essas experiências desenvolvendo sistemas, produtos digitais e soluções pensadas para problemas que existem fora da tela.",
      ],
      processLabel: "COMO EU TRABALHO",
      process: [
        { n: "01", t: "ENTENDER A OPERAÇÃO" },
        { n: "02", t: "MAPEAR O NEGÓCIO" },
        { n: "03", t: "REMOVER A FRICÇÃO" },
        { n: "04", t: "DESENHAR O SISTEMA" },
        { n: "05", t: "CONSTRUIR E VALIDAR EM CONDIÇÕES REAIS" },
        { n: "06", t: "ENTREGAR, MEDIR E MELHORAR" },
      ],
    },
    services: {
      label: "08 / SERVIÇOS E CAPACIDADES",
      title: "O QUE POSSO CONSTRUIR",
      groups: [
        {
          t: "PRODUTO",
          items: ["Product thinking", "UX/UI", "Jornada do cliente", "Comércio digital", "SaaS", "Conversão"],
        },
        {
          t: "ENGENHARIA",
          items: ["React", "TypeScript", "JavaScript", "APIs", "PostgreSQL", "Supabase", "Autenticação", "RLS", "Realtime", "Git / GitHub", "Vercel"],
        },
        {
          t: "OPERAÇÕES",
          items: ["Mapeamento de processos", "Logística", "Estoque", "Fluxos operacionais", "Processos de negócio", "Organização de projetos"],
        },
        {
          t: "EM EXPANSÃO",
          items: ["n8n", "Automação de processos", "Workflows com IA", "Arquitetura de software"],
        },
      ],
    },
    contact: {
      label: "09 / CONTATO",
      title1: "TEM ALGO",
      title2: "QUE PRECISA FUNCIONAR?",
      accent: "Vamos construir.",
      careerTitle: "OPORTUNIDADE DE CARREIRA",
      careerText:
        "Aberto a posições em desenvolvimento de software, full stack, sistemas empresariais e produtos digitais.",
      projectTitle: "INICIAR UM PROJETO",
      projectText:
        "Sites, aplicações, sistemas, automações e soluções personalizadas via AURHEA.",
      channels: "CANAIS",
      email: "E-MAIL",
      whatsapp: "WHATSAPP",
      linkedin: "LINKEDIN",
      github: "GITHUB",
      instagram: "INSTAGRAM",
      aurhea: "AURHEA",
      viewProfile: "VER PERFIL",
      visit: "VISITAR",
    },
    footer: {
      role: "Founder & Developer — AURHEA",
      place: "Caxias do Sul · RS · Brasil",
      rights: "Todos os direitos reservados.",
      signature: "PRODUTO / DESIGN / DESENVOLVIMENTO",
      top: "VOLTAR AO TOPO",
    },
  },
  en: {
    nav: {
      work: "WORK",
      profile: "PROFILE",
      systems: "SYSTEMS",
      aurhea: "AURHEA",
      contact: "CONTACT",
      menu: "MENU",
      close: "CLOSE",
      openMenu: "Open navigation menu",
      closeMenu: "Close navigation menu",
      skip: "Skip to content",
      langLabel: "Switch language to Portuguese",
    },
    hero: {
      tag: "AR / 2026",
      place: "CAXIAS DO SUL · BRAZIL",
      status: "OPEN TO OPPORTUNITIES",
      disciplines: ["SOFTWARE", "SYSTEMS", "AUTOMATION", "OPERATIONS"],
      headline: "I build digital products",
      headlineAccent: "for real-world operations.",
      portraitAlt: "Portrait of Antony Rodrigues",
      ctaWork: "SELECTED WORK",
      ctaContact: "START A PROJECT",
      explore: "EXPLORE",
    },
    marquee: [
      "SOFTWARE",
      "SYSTEMS",
      "AUTOMATION",
      "OPERATIONS",
      "PRODUCT",
      "FULL STACK",
      "AURHEA",
    ],
    manifesto: {
      label: "02 / MANIFESTO",
      line1: "SOFTWARE ISN'T",
      line2: "THE STARTING POINT.",
      accent: "The operation is.",
      quote:
        "I didn't start in software. I started where software has to work.",
    },
    proof: {
      label: "03 / CREDIBILITY",
      title: "WHAT THE WORK STANDS ON",
      items: [
        { k: "AURHEA", v: "Founder & Developer", d: "My own technology company, founded in March 2026." },
        { k: "OPERATIONS", v: "Logistics · Industry", d: "Years inside real processes before writing software for them." },
        { k: "PRODUCTION", v: "Projects in real use", d: "Sites, systems and platforms delivered and running for clients." },
        { k: "EDUCATION", v: "Software Engineering — FSG", d: "Degree started in 2025. Technical background in logistics at SENAI." },
      ],
    },
    systems: {
      label: "04 / SELECTED SYSTEMS",
      title: "HOW I BUILD SYSTEMS",
      intro:
        "Architecture designed from the process, not from the technology. Below, the conceptual design of the main technical case.",
      caseTitle: "PORCO MORTO",
      caseSub: "RESTAURANT OPERATIONS SYSTEM",
      flow: [
        "STOREFRONT",
        "ORDER SUBMISSION",
        "AUTHORITATIVE BACKEND",
        "POSTGRESQL",
        "REALTIME",
        "ADMIN",
        "FINANCE / PRINT / OPERATIONS",
      ],
      pillars: [
        { t: "AUTHORITATIVE BACKEND", d: "Business rules validated on the server, never on the client." },
        { t: "DATA & ACCESS", d: "PostgreSQL with row-level access policies and authentication." },
        { t: "REALTIME", d: "Orders and status propagated to the operation in realtime." },
        { t: "RELIABILITY", d: "Order idempotency, rate limiting and input validation." },
      ],
    },
    work: {
      label: "05 / SELECTED WORK",
      title: "PROJECTS",
      intro: "Independent product, design and development — 2026.",
      view: "VIEW PROJECT",
      soon: "PRIVATE PREVIEW",
      noLink: "Internal case · no public URL",
    },
    timeline: {
      label: "06 / TRAJECTORY",
      title: "FROM OPERATIONS TO SOFTWARE.",
      steps: [
        { k: "LOGISTICS", v: "SENAI — technical training" },
        { k: "FIELD OPERATIONS", v: "Expresso São Miguel" },
        { k: "INDUSTRIAL OPERATIONS", v: "SV Engenharia e Serviços — current" },
        { k: "SOFTWARE", v: "Software Engineering — FSG, since 2025" },
        { k: "AURHEA", v: "Founder & Developer — Mar/2026" },
      ],
    },
    story: {
      label: "07 / STORY",
      title: "THE PROBLEM COMES BEFORE THE TECHNOLOGY.",
      paragraphs: [
        "My path didn't start in software. It started in real operations — logistics, material handling, inventory and industrial environments.",
        "Understanding how processes actually work made me see technology differently: not as an end, but as a tool to organize, automate and build better businesses.",
        "Today I connect those experiences by developing systems, digital products and solutions designed for problems that exist off the screen.",
      ],
      processLabel: "HOW I WORK",
      process: [
        { n: "01", t: "UNDERSTAND THE OPERATION" },
        { n: "02", t: "MAP THE BUSINESS" },
        { n: "03", t: "REMOVE THE FRICTION" },
        { n: "04", t: "DESIGN THE SYSTEM" },
        { n: "05", t: "BUILD AND VALIDATE IN REAL CONDITIONS" },
        { n: "06", t: "SHIP, MEASURE AND IMPROVE" },
      ],
    },
    services: {
      label: "08 / SERVICES & CAPABILITIES",
      title: "WHAT I CAN BUILD",
      groups: [
        { t: "PRODUCT", items: ["Product thinking", "UX/UI", "Customer journey", "Digital commerce", "SaaS", "Conversion"] },
        { t: "ENGINEERING", items: ["React", "TypeScript", "JavaScript", "APIs", "PostgreSQL", "Supabase", "Authentication", "RLS", "Realtime", "Git / GitHub", "Vercel"] },
        { t: "OPERATIONS", items: ["Process mapping", "Logistics", "Inventory", "Operational flows", "Business processes", "Project organization"] },
        { t: "EXPANDING INTO", items: ["n8n", "Process automation", "AI workflows", "Software architecture"] },
      ],
    },
    contact: {
      label: "09 / CONTACT",
      title1: "HAVE SOMETHING",
      title2: "THAT NEEDS TO WORK?",
      accent: "Let's build it.",
      careerTitle: "CAREER OPPORTUNITY",
      careerText:
        "Open to roles in software development, full stack, enterprise systems and digital products.",
      projectTitle: "START A PROJECT",
      projectText:
        "Websites, applications, systems, automation and custom solutions through AURHEA.",
      channels: "CHANNELS",
      email: "EMAIL",
      whatsapp: "WHATSAPP",
      linkedin: "LINKEDIN",
      github: "GITHUB",
      instagram: "INSTAGRAM",
      aurhea: "AURHEA",
      viewProfile: "VIEW PROFILE",
      visit: "VISIT",
    },
    footer: {
      role: "Founder & Developer — AURHEA",
      place: "Caxias do Sul · RS · Brazil",
      rights: "All rights reserved.",
      signature: "PRODUCT / DESIGN / DEVELOPMENT",
      top: "BACK TO TOP",
    },
  },
} as const;

export type Copy = (typeof copy)["pt"];